### ISSUE TITLE
[Chore] 스위프트 린트 추가하고 설정하기

### ISSUE THREAD

**Issue by EuniceNam** [SnoopClass/Eunice_Student_IKEA#1]
스위프트스러운 코딩을 위해 스위프트린트를 프로젝트에 적용하도록 설정합니다. 

- 따로 이슈를 쓴 이유: 따로 브랜치를 파려고 하기 때문입니다. 
  - 따로 브랜치를 쓰는 이유: 전에 [멘토분이 하신다는 방법](https://grizzly-guide-50a.notion.site/220602-6fcaa4aa0d2b4dad90a577284ed131cb)을 따라가보려고 하기 때문입니다. 

**참고**
- 스위프트린트(SwiftLint): 스위프트의 스타일 규칙을 강제하는 도구입니다. 
  - [규칙 안내 페이지](https://realm.github.io/SwiftLint/rule-directory.html)
  - [설치 안내가 있는 깃헙](https://github.com/realm/SwiftLint)
- [SwiftLint 설치 및 설정 방법(노션)](https://grizzly-guide-50a.notion.site/SwiftLint-40d96e0ffdee4824905c16b049131861)

**Comment by MARKGRAYSIRO** [comment]
화이팅이에요 유니스!

**Comment by compuTasha** [comment]
저희 이슈 제목은 Commit Naming Convention 을 활용하기로 정해서
`[Chore] SwiftLint 추가 및 설정 `
이런 식으로 변경해야 할 것 같아요!

**Comment by EuniceNam** [comment]
> 저희 이슈 제목은 Commit Naming Convention 을 활용하기로 정해서
> `[Chore] SwiftLint 추가 및 설정 `
> 이런 식으로 변경해야 할 것 같아요!

아하 PR과 헷갈렸네요.. 코멘트 감사합니다.
